- name: Remove the host list file if it exists
  hosts: localhost
  connection: local
  tasks:
    - name: Remove the file
      file:
        path: 'files/server_list.txt'
        state: absent
- name: Get IP of each server
  hosts: pg-*
  tasks:
    - name: Add the list of standby servers to a file
      local_action:
        module: lineinfile
        path: 'files/server_list.txt'
        create: yes
        line: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        state: present

