- name: Create a Digital Ocean Droplet for Primary
  hosts: localhost
  connection: local
  vars:
    server: pg-primary
  roles:
    - create-digitalocean

- name: Use create-digitalocean Role to create multiple Standby Instance
  hosts: localhost
  connection: local
  vars:
  tasks:
    - name: Create Digital Ocean droplet for Standby
      include_role:
        name: create-digitalocean
      vars:
        server: 'pg-standby{{ standby_id }}'
      with_sequence: count='{{ standby_count }}'
      loop_control:
        loop_var: standby_id
