- name: Create an EC2 instance for Primary
  hosts: localhost
  connection: local
  vars:
    server: pg-primary
  roles:
    - create-ec2

- name: Use create-ec2 Role to create multiple Standby Instance
  hosts: localhost
  connection: local
  vars:
  tasks:
    - name: Create EC2 instances for Standby
      include_role:
        name: create-ec2
      vars:
        server: 'pg-standby{{ standby_id }}'
      with_sequence: count='{{ standby_count }}'
      loop_control:
        loop_var: standby_id
