
- when: (provider=='digitalocean')
  import_playbook: digital-ocean-server-setup-playbook.yml

- when: (provider=='aws')
  import_playbook: ec2-server-setup-playbook.yml


- name: Setup EDB Repository
  hosts: pg_servers
  roles:
    - edb-setup

- import_playbook: primary-instance-playbook.yml
- import_playbook: standby-setup-playbook.yml

