    - name: Add EDB Repo
      yum_repository: 
        name: edb
        baseurl: "{{ lookup('ini', 'repo.url section=edb_yum_repo file={{ cred_file }}') }}"
        enabled: yes
        state: present
        description: EnterpriseDB Repos $releasever - $basearch
        file: edb_package_repo
        gpgcheck: no
        username: "{{ lookup('ini', 'repo.user section=edb_yum_repo file={{ cred_file }}') }}" 
        password: "{{ lookup('ini', 'repo.password section=edb_yum_repo file={{ cred_file }}') }}"
      become: true

    - name: Refresh yum meta
      command: yum update meta
      become: true

    - name: Install the repository rpm
      yum: 
        name: edb-repo
        state: present
      become: true

    - name: Install Enterprise Linux Repo
      yum:
        name: epel-release
        state: installed
      become: true

    - name: Set username password
      replace:
        path: '{{ edb_repo_file }}'
        regexp: '<username>:<password>'
        replace: "{{ lookup('ini', 'repo.user section=edb_yum_repo file={{ cred_file }}') }}:{{ lookup('ini', 'repo.password section=edb_yum_repo file={{ cred_file }}') }}"
      become: true

    - name: Enable repos
      ini_file:
        path: '{{ edb_repo_file }}'
        section: '{{ item }}'
        option: enabled
        value: 1
      with_items: '{{ repo_list }}'
      become: true

    - name: Refresh yum meta
      command: yum update meta
      become: true

