INITDB_PARAM: "-k --no-redwood-compat"
PGDATA: /pg/data
replication_user: repl_user
RANDOM_PASSWD_FILE: pg_passwd
# BEGIN ANSIBLE MANAGED BLOCK
ansible_host: 139.59.225.237
ansible_user: root
host_region: sgp1
host_os: CentOS
os_version: 7
# END ANSIBLE MANAGED BLOCK
