
       - name: Add EDB Group
         group:
           name: '{{ PGOWNER }}'
           state: present
         become: true

       - name: Add EDB Users
         user:
           name: '{{ PGOWNER }}'
           state: present
         become: true
